# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      DEPLOYMENT_ENVIRONMENT: 
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
      S3_ARN:
        required: true
        type: string

env: 
  AZ1: ${{ secrets.AZ1 }}
  AZ3: ${{ vars.AZ3 }}
  AZ4: ${{ secrets.AZ4 }}
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: ${{ inputs.BRANCH_NAME == 'refs/heads/release' }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: | 
          echo ${{ inputs.BRANCH_NAME }}
          echo Hello, world!
          echo ${{ secrets.AZ4 }}
          echo ${{ env.AZ3 }}
          echo ${{ secrets.AZ1 }}

      - name: Set AWS region
        run: |
          if [ ${{ inputs.DEPLOYMENT_ENVIRONMENT }} == 'AZ4' ]; then
            AWS_REGION=me-central-1
          else
            AWS_REGION=ap-south-1
          fi
          echo "AWS_REGION=$AWS_REGION"


      - name: Update task
        if:  ${{ inputs.DEPLOYMENT_ENVIRONMENT }} == 'AZ4'
        run: |
          AWS_REGION=ap-south-1
          echo $AWS_REGION
          sed -i "s|IMAGE_TAG|${{inputs.ENVIRONMENT}}|g" .github/task-definition.json
          sed -i "s|S3_ARN|${{inputs.S3_ARN}}|g" .github/task-definition.json

      - name: Update task
        if: ${{ inputs.DEPLOYMENT_ENVIRONMENT }} == 'AZ4'
        run: | 
          AWS_REGION=me-central-1
          echo $AWS_REGION
          sed -i "s|IMAGE_TAG|${{inputs.ENVIRONMENT}}|g" .github/task-definition.json
          sed -i "s|S3_ARN|${{inputs.S3_ARN}}|g" .github/task-definition.json


      - name: Print task definition 
        run: |
          cat .github/task-definition.json

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          if [[ ${{ github.event_name }} == "push" &&  ${{ github.ref_name }} == "main" ]]; then
          echo Hello, world!
          fi
