# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      DEPLOYMENT_ENVIRONMENT: 
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      S3_ARN:
        required: true
        type: string

env: 
  AZ1: ${{ secrets.AZ1 }}
  AZ3: ${{ secrets.AZ3 }}
  AZ4: ${{ secrets.AZ4 }}
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: | 
          echo Hello, world!
          echo env.AZ3
          echo env.AZ1
          echo env.AZ4

      - name: Set AWS region
        run: |
          echo "::set-env name=AWS_REGION::${{ env.DEPLOYMENT_ENVIRONMENT == 'AZ4' ? 'me-central-1' : 'ap-south-1' }}"


      - name: Update task
        if: env.AWS_REGION == 'ap-south-1'
        run: |
          echo env.AWS_REGION
          sed -i "s|IMAGE_TAG|${{inputs.ENVIRONMENT}}|g" .github/task-definition.json
          sed -i "s|S3_ARN|${{inputs.S3_ARN}}|g" .github/task-definition.json

      - name: Update task
        if: env.AWS_REGION == 'me-central-1'
        run: | 
          echo "INside az4"
          echo env.AWS_REGION
          sed -i "s|IMAGE_TAG|${{inputs.ENVIRONMENT}}|g" .github/task-definition.json
          sed -i "s|S3_ARN|${{inputs.S3_ARN}}|g" .github/task-definition.json


      - name: Print task definition 
        run: |
          cat .github/task-definition.json

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          if [[ ${{ github.event_name }} == "push" &&  ${{ github.ref_name }} == "main" ]]; then
          echo Hello, world!
          fi
