
name: push

# Controls when the workflow will run
on:
  release:
    types:
      - released
      - prereleased
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Choose environment'
        required: true
        type: choice
        options:
          - pit
          - prod
          - kcb_beta
          - najm_beta
      RELEASE_NAME:
        description: 'Release name'
        required: true
        type: string


jobs:
  test: 
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Update manifest file
        run: |
          echo "${{github.ref}}"
          branch_name="update-image-tag-${{github.run_id}} "
          echo "$branch_name"
          shaa=$(curl https://google.com/"$branch_name")

      - name: Get Branch Name
        id: get_branch
        run: |
          SHA="${{ github.sha }}" # Use github.sha for the release commit
          BRANCH=$(git branch --contains "$SHA" | grep -v '\*' | tr -d ' ') # Find the branch
          echo "::set-output name=branch::$BRANCH" # Set the output variable

      - name: Use Branch Name
        run: |
          echo "Branch Name: ${{ steps.get_branch.outputs.branch }}"
          branch_name="update-image-tag-${{ github.run_id }}-${{ steps.get_branch.outputs.branch }}" # Include branch name in your tag
          echo "$branch_name"
          
  # This workflow contains a single job called "build"
  blank:
    name: blank
    uses: ./.github/workflows/blank.yml
    with:
      S3_ARN: arn:aws:s3:::ecs-enviroment-file/az1/core-backend.env
      ENVIRONMENT: production
      DEPLOYMENT_ENVIRONMENT: ap-south-1
      BRANCH_NAME: ${{ steps.get_branch.outputs.branch }}

